keep: ""
APIToken: cchi48mv9mc753cgsrjg
BotName: 机器人
probability: 2
dhreplystart: ""
lxdhreplystart: ""
twreplystart: ""
xxreplystart: ""
ydljreplystart: ""
model: xl
max_tokens: 256
temperature: 0.85
top_p: 0.95
top_k: 50
n: 2
stop: "\n"
twstop: 。
dhcmdstart: welm
lxdhcmdstart: lxdh
twcmdstart: 提问
xxcmdstart: 续写
ydlicmdstart: 阅读理解
Guide: no
